services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./Backend/Backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/project # Use the container name 'mongo' for the URI

  frontend:
    build:
      context: ./vite-react-app
    container_name: frontend
    ports:
      - "5173:80" # Map port 80 in the container to port 5173 on the host
    depends_on:
      - backend

volumes:
  mongo_data: